# Generated by Django 5.0.1 on 2024-01-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_flashcard', '0005_desafio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='status',
            field=models.CharField(default='aberto', max_length=50),
        ),
    ]
